//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace StocktakrClient.com.stocktakr {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="POSItemHandlerSoap", Namespace="http://stocktakr.com/")]
    public partial class POSItemHandler : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestConnectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOrReplaceItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSuppliersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStocktakeTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteStocktakeTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPurchaseOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePurchaseOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceivedGoodsOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteReceivedGoodsOrdersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public POSItemHandler() {
            this.Url = "http://stocktakr.com/services/POSItemHandler.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event TestConnectionCompletedEventHandler TestConnectionCompleted;
        
        /// <remarks/>
        public event UpdateOrReplaceItemsCompletedEventHandler UpdateOrReplaceItemsCompleted;
        
        /// <remarks/>
        public event UpdateSuppliersCompletedEventHandler UpdateSuppliersCompleted;
        
        /// <remarks/>
        public event GetStocktakeTransactionsCompletedEventHandler GetStocktakeTransactionsCompleted;
        
        /// <remarks/>
        public event DeleteStocktakeTransactionsCompletedEventHandler DeleteStocktakeTransactionsCompleted;
        
        /// <remarks/>
        public event GetPurchaseOrdersCompletedEventHandler GetPurchaseOrdersCompleted;
        
        /// <remarks/>
        public event DeletePurchaseOrdersCompletedEventHandler DeletePurchaseOrdersCompleted;
        
        /// <remarks/>
        public event GetReceivedGoodsOrdersCompletedEventHandler GetReceivedGoodsOrdersCompleted;
        
        /// <remarks/>
        public event DeleteReceivedGoodsOrdersCompletedEventHandler DeleteReceivedGoodsOrdersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/HelloWorld", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/TestConnection", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse TestConnection(int storeID, string password) {
            object[] results = this.Invoke("TestConnection", new object[] {
                        storeID,
                        password});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TestConnectionAsync(int storeID, string password) {
            this.TestConnectionAsync(storeID, password, null);
        }
        
        /// <remarks/>
        public void TestConnectionAsync(int storeID, string password, object userState) {
            if ((this.TestConnectionOperationCompleted == null)) {
                this.TestConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestConnectionOperationCompleted);
            }
            this.InvokeAsync("TestConnection", new object[] {
                        storeID,
                        password}, this.TestConnectionOperationCompleted, userState);
        }
        
        private void OnTestConnectionOperationCompleted(object arg) {
            if ((this.TestConnectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestConnectionCompleted(this, new TestConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/UpdateOrReplaceItems", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse UpdateOrReplaceItems(int storeID, string password, string compressedItems, bool replaceAll) {
            object[] results = this.Invoke("UpdateOrReplaceItems", new object[] {
                        storeID,
                        password,
                        compressedItems,
                        replaceAll});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateOrReplaceItemsAsync(int storeID, string password, string compressedItems, bool replaceAll) {
            this.UpdateOrReplaceItemsAsync(storeID, password, compressedItems, replaceAll, null);
        }
        
        /// <remarks/>
        public void UpdateOrReplaceItemsAsync(int storeID, string password, string compressedItems, bool replaceAll, object userState) {
            if ((this.UpdateOrReplaceItemsOperationCompleted == null)) {
                this.UpdateOrReplaceItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOrReplaceItemsOperationCompleted);
            }
            this.InvokeAsync("UpdateOrReplaceItems", new object[] {
                        storeID,
                        password,
                        compressedItems,
                        replaceAll}, this.UpdateOrReplaceItemsOperationCompleted, userState);
        }
        
        private void OnUpdateOrReplaceItemsOperationCompleted(object arg) {
            if ((this.UpdateOrReplaceItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateOrReplaceItemsCompleted(this, new UpdateOrReplaceItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/UpdateSuppliers", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse UpdateSuppliers(int storeID, string password, LocalSupplier[] suppliers) {
            object[] results = this.Invoke("UpdateSuppliers", new object[] {
                        storeID,
                        password,
                        suppliers});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSuppliersAsync(int storeID, string password, LocalSupplier[] suppliers) {
            this.UpdateSuppliersAsync(storeID, password, suppliers, null);
        }
        
        /// <remarks/>
        public void UpdateSuppliersAsync(int storeID, string password, LocalSupplier[] suppliers, object userState) {
            if ((this.UpdateSuppliersOperationCompleted == null)) {
                this.UpdateSuppliersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSuppliersOperationCompleted);
            }
            this.InvokeAsync("UpdateSuppliers", new object[] {
                        storeID,
                        password,
                        suppliers}, this.UpdateSuppliersOperationCompleted, userState);
        }
        
        private void OnUpdateSuppliersOperationCompleted(object arg) {
            if ((this.UpdateSuppliersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSuppliersCompleted(this, new UpdateSuppliersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/GetStocktakeTransactions", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse GetStocktakeTransactions(int storeID, string password) {
            object[] results = this.Invoke("GetStocktakeTransactions", new object[] {
                        storeID,
                        password});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetStocktakeTransactionsAsync(int storeID, string password) {
            this.GetStocktakeTransactionsAsync(storeID, password, null);
        }
        
        /// <remarks/>
        public void GetStocktakeTransactionsAsync(int storeID, string password, object userState) {
            if ((this.GetStocktakeTransactionsOperationCompleted == null)) {
                this.GetStocktakeTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStocktakeTransactionsOperationCompleted);
            }
            this.InvokeAsync("GetStocktakeTransactions", new object[] {
                        storeID,
                        password}, this.GetStocktakeTransactionsOperationCompleted, userState);
        }
        
        private void OnGetStocktakeTransactionsOperationCompleted(object arg) {
            if ((this.GetStocktakeTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStocktakeTransactionsCompleted(this, new GetStocktakeTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/DeleteStocktakeTransactions", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse DeleteStocktakeTransactions(int storeID, string password) {
            object[] results = this.Invoke("DeleteStocktakeTransactions", new object[] {
                        storeID,
                        password});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteStocktakeTransactionsAsync(int storeID, string password) {
            this.DeleteStocktakeTransactionsAsync(storeID, password, null);
        }
        
        /// <remarks/>
        public void DeleteStocktakeTransactionsAsync(int storeID, string password, object userState) {
            if ((this.DeleteStocktakeTransactionsOperationCompleted == null)) {
                this.DeleteStocktakeTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteStocktakeTransactionsOperationCompleted);
            }
            this.InvokeAsync("DeleteStocktakeTransactions", new object[] {
                        storeID,
                        password}, this.DeleteStocktakeTransactionsOperationCompleted, userState);
        }
        
        private void OnDeleteStocktakeTransactionsOperationCompleted(object arg) {
            if ((this.DeleteStocktakeTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteStocktakeTransactionsCompleted(this, new DeleteStocktakeTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/GetPurchaseOrders", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse GetPurchaseOrders(int storeID, string password) {
            object[] results = this.Invoke("GetPurchaseOrders", new object[] {
                        storeID,
                        password});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetPurchaseOrdersAsync(int storeID, string password) {
            this.GetPurchaseOrdersAsync(storeID, password, null);
        }
        
        /// <remarks/>
        public void GetPurchaseOrdersAsync(int storeID, string password, object userState) {
            if ((this.GetPurchaseOrdersOperationCompleted == null)) {
                this.GetPurchaseOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPurchaseOrdersOperationCompleted);
            }
            this.InvokeAsync("GetPurchaseOrders", new object[] {
                        storeID,
                        password}, this.GetPurchaseOrdersOperationCompleted, userState);
        }
        
        private void OnGetPurchaseOrdersOperationCompleted(object arg) {
            if ((this.GetPurchaseOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPurchaseOrdersCompleted(this, new GetPurchaseOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/DeletePurchaseOrders", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse DeletePurchaseOrders(int storeID, string password) {
            object[] results = this.Invoke("DeletePurchaseOrders", new object[] {
                        storeID,
                        password});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeletePurchaseOrdersAsync(int storeID, string password) {
            this.DeletePurchaseOrdersAsync(storeID, password, null);
        }
        
        /// <remarks/>
        public void DeletePurchaseOrdersAsync(int storeID, string password, object userState) {
            if ((this.DeletePurchaseOrdersOperationCompleted == null)) {
                this.DeletePurchaseOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePurchaseOrdersOperationCompleted);
            }
            this.InvokeAsync("DeletePurchaseOrders", new object[] {
                        storeID,
                        password}, this.DeletePurchaseOrdersOperationCompleted, userState);
        }
        
        private void OnDeletePurchaseOrdersOperationCompleted(object arg) {
            if ((this.DeletePurchaseOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePurchaseOrdersCompleted(this, new DeletePurchaseOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/GetReceivedGoodsOrders", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse GetReceivedGoodsOrders(int storeID, string password) {
            object[] results = this.Invoke("GetReceivedGoodsOrders", new object[] {
                        storeID,
                        password});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetReceivedGoodsOrdersAsync(int storeID, string password) {
            this.GetReceivedGoodsOrdersAsync(storeID, password, null);
        }
        
        /// <remarks/>
        public void GetReceivedGoodsOrdersAsync(int storeID, string password, object userState) {
            if ((this.GetReceivedGoodsOrdersOperationCompleted == null)) {
                this.GetReceivedGoodsOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceivedGoodsOrdersOperationCompleted);
            }
            this.InvokeAsync("GetReceivedGoodsOrders", new object[] {
                        storeID,
                        password}, this.GetReceivedGoodsOrdersOperationCompleted, userState);
        }
        
        private void OnGetReceivedGoodsOrdersOperationCompleted(object arg) {
            if ((this.GetReceivedGoodsOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceivedGoodsOrdersCompleted(this, new GetReceivedGoodsOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stocktakr.com/DeleteReceivedGoodsOrders", RequestNamespace="http://stocktakr.com/", ResponseNamespace="http://stocktakr.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ItemResponse DeleteReceivedGoodsOrders(int storeID, string password) {
            object[] results = this.Invoke("DeleteReceivedGoodsOrders", new object[] {
                        storeID,
                        password});
            return ((ItemResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteReceivedGoodsOrdersAsync(int storeID, string password) {
            this.DeleteReceivedGoodsOrdersAsync(storeID, password, null);
        }
        
        /// <remarks/>
        public void DeleteReceivedGoodsOrdersAsync(int storeID, string password, object userState) {
            if ((this.DeleteReceivedGoodsOrdersOperationCompleted == null)) {
                this.DeleteReceivedGoodsOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteReceivedGoodsOrdersOperationCompleted);
            }
            this.InvokeAsync("DeleteReceivedGoodsOrders", new object[] {
                        storeID,
                        password}, this.DeleteReceivedGoodsOrdersOperationCompleted, userState);
        }
        
        private void OnDeleteReceivedGoodsOrdersOperationCompleted(object arg) {
            if ((this.DeleteReceivedGoodsOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteReceivedGoodsOrdersCompleted(this, new DeleteReceivedGoodsOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stocktakr.com/")]
    public partial class ItemResponse {
        
        private bool is_errorField;
        
        private string errorMessageField;
        
        private LocalItem[] localItemsField;
        
        private LocalStocktakeTransaction[] localStocktakeTransactionsField;
        
        private LocalPurchaseOrder[] localPurchaseOrdersField;
        
        private LocalReceivedGoodsOrder[] localReceivedGoodsOrdersField;
        
        /// <remarks/>
        public bool is_error {
            get {
                return this.is_errorField;
            }
            set {
                this.is_errorField = value;
            }
        }
        
        /// <remarks/>
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public LocalItem[] localItems {
            get {
                return this.localItemsField;
            }
            set {
                this.localItemsField = value;
            }
        }
        
        /// <remarks/>
        public LocalStocktakeTransaction[] localStocktakeTransactions {
            get {
                return this.localStocktakeTransactionsField;
            }
            set {
                this.localStocktakeTransactionsField = value;
            }
        }
        
        /// <remarks/>
        public LocalPurchaseOrder[] localPurchaseOrders {
            get {
                return this.localPurchaseOrdersField;
            }
            set {
                this.localPurchaseOrdersField = value;
            }
        }
        
        /// <remarks/>
        public LocalReceivedGoodsOrder[] localReceivedGoodsOrders {
            get {
                return this.localReceivedGoodsOrdersField;
            }
            set {
                this.localReceivedGoodsOrdersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stocktakr.com/")]
    public partial class LocalItem {
        
        private string product_codeField;
        
        private string product_barcodeField;
        
        private string supplier_codeField;
        
        private string descriptionField;
        
        private decimal cost_priceField;
        
        private decimal sale_priceField;
        
        private double quantityField;
        
        private bool is_staticField;
        
        private System.DateTime modified_datetimeField;
        
        /// <remarks/>
        public string product_code {
            get {
                return this.product_codeField;
            }
            set {
                this.product_codeField = value;
            }
        }
        
        /// <remarks/>
        public string product_barcode {
            get {
                return this.product_barcodeField;
            }
            set {
                this.product_barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string supplier_code {
            get {
                return this.supplier_codeField;
            }
            set {
                this.supplier_codeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal cost_price {
            get {
                return this.cost_priceField;
            }
            set {
                this.cost_priceField = value;
            }
        }
        
        /// <remarks/>
        public decimal sale_price {
            get {
                return this.sale_priceField;
            }
            set {
                this.sale_priceField = value;
            }
        }
        
        /// <remarks/>
        public double quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public bool is_static {
            get {
                return this.is_staticField;
            }
            set {
                this.is_staticField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime modified_datetime {
            get {
                return this.modified_datetimeField;
            }
            set {
                this.modified_datetimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stocktakr.com/")]
    public partial class LocalSupplier {
        
        private string supplier_codeField;
        
        private string nameField;
        
        /// <remarks/>
        public string supplier_code {
            get {
                return this.supplier_codeField;
            }
            set {
                this.supplier_codeField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stocktakr.com/")]
    public partial class LocalReceivedGoodsOrderItem {
        
        private string product_codeField;
        
        private string product_barcodeField;
        
        private string descriptionField;
        
        private double quantityField;
        
        /// <remarks/>
        public string product_code {
            get {
                return this.product_codeField;
            }
            set {
                this.product_codeField = value;
            }
        }
        
        /// <remarks/>
        public string product_barcode {
            get {
                return this.product_barcodeField;
            }
            set {
                this.product_barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stocktakr.com/")]
    public partial class LocalReceivedGoodsOrder {
        
        private int receivedgoodsorder_idField;
        
        private string supplier_codeField;
        
        private string personField;
        
        private System.DateTime order_datetimeField;
        
        private LocalReceivedGoodsOrderItem[] itemListField;
        
        /// <remarks/>
        public int receivedgoodsorder_id {
            get {
                return this.receivedgoodsorder_idField;
            }
            set {
                this.receivedgoodsorder_idField = value;
            }
        }
        
        /// <remarks/>
        public string supplier_code {
            get {
                return this.supplier_codeField;
            }
            set {
                this.supplier_codeField = value;
            }
        }
        
        /// <remarks/>
        public string person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime order_datetime {
            get {
                return this.order_datetimeField;
            }
            set {
                this.order_datetimeField = value;
            }
        }
        
        /// <remarks/>
        public LocalReceivedGoodsOrderItem[] itemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stocktakr.com/")]
    public partial class LocalPurchaseOrderItem {
        
        private string product_codeField;
        
        private string product_barcodeField;
        
        private string descriptionField;
        
        private double quantityField;
        
        /// <remarks/>
        public string product_code {
            get {
                return this.product_codeField;
            }
            set {
                this.product_codeField = value;
            }
        }
        
        /// <remarks/>
        public string product_barcode {
            get {
                return this.product_barcodeField;
            }
            set {
                this.product_barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stocktakr.com/")]
    public partial class LocalPurchaseOrder {
        
        private int purchaseorder_idField;
        
        private string supplier_codeField;
        
        private string supplier_nameField;
        
        private string personField;
        
        private System.DateTime order_datetimeField;
        
        private LocalPurchaseOrderItem[] itemListField;
        
        /// <remarks/>
        public int purchaseorder_id {
            get {
                return this.purchaseorder_idField;
            }
            set {
                this.purchaseorder_idField = value;
            }
        }
        
        /// <remarks/>
        public string supplier_code {
            get {
                return this.supplier_codeField;
            }
            set {
                this.supplier_codeField = value;
            }
        }
        
        /// <remarks/>
        public string supplier_name {
            get {
                return this.supplier_nameField;
            }
            set {
                this.supplier_nameField = value;
            }
        }
        
        /// <remarks/>
        public string person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime order_datetime {
            get {
                return this.order_datetimeField;
            }
            set {
                this.order_datetimeField = value;
            }
        }
        
        /// <remarks/>
        public LocalPurchaseOrderItem[] itemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stocktakr.com/")]
    public partial class LocalStocktakeTransaction {
        
        private string product_codeField;
        
        private string product_barcodeField;
        
        private string descriptionField;
        
        private double quantityField;
        
        private string personField;
        
        private System.DateTime stocktake_datetimeField;
        
        /// <remarks/>
        public string product_code {
            get {
                return this.product_codeField;
            }
            set {
                this.product_codeField = value;
            }
        }
        
        /// <remarks/>
        public string product_barcode {
            get {
                return this.product_barcodeField;
            }
            set {
                this.product_barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime stocktake_datetime {
            get {
                return this.stocktake_datetimeField;
            }
            set {
                this.stocktake_datetimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TestConnectionCompletedEventHandler(object sender, TestConnectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateOrReplaceItemsCompletedEventHandler(object sender, UpdateOrReplaceItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateOrReplaceItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateOrReplaceItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateSuppliersCompletedEventHandler(object sender, UpdateSuppliersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSuppliersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSuppliersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStocktakeTransactionsCompletedEventHandler(object sender, GetStocktakeTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStocktakeTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStocktakeTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteStocktakeTransactionsCompletedEventHandler(object sender, DeleteStocktakeTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteStocktakeTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteStocktakeTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetPurchaseOrdersCompletedEventHandler(object sender, GetPurchaseOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPurchaseOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPurchaseOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeletePurchaseOrdersCompletedEventHandler(object sender, DeletePurchaseOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePurchaseOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePurchaseOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetReceivedGoodsOrdersCompletedEventHandler(object sender, GetReceivedGoodsOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceivedGoodsOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceivedGoodsOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteReceivedGoodsOrdersCompletedEventHandler(object sender, DeleteReceivedGoodsOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteReceivedGoodsOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteReceivedGoodsOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ItemResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ItemResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591